language: java

jdk:
 - openjdk8
 
services:
 - docker

script:
 - mvn install
 - docker build -t travis .
 
after_success:
 - docker login -u $DockerHub_User -p $DockerHub_Password
 - docker tag travis $DOCKER_USER/travis:$TRAVIS_BUILD_NUMBER
 - docker push $DOCKER_USER/travis:$TRAVIS_BUILD_NUMBER
 - docker tag travis $DOCKER_USER/travis:latest
 - docker push $DOCKER_USER/travis:latest
