language: java

jdk:
 - openjdk8
 
services:
 - docker

script:
 - mvn install
 
after_success:
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
 - docker build -t kubernetes .
 - docker images
 - docker tag kubernetes $DOCKER_USERNAME/kubernetes
 - docker push $DOCKER_USERNAME/kubernetes
