language: java

jdk:
 - openjdk8
 
services:
 - docker
 
script:
 - mvn install
 - docker build -t kubernetes .
 
after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker tag back $DOCKER_USERNAME/back:$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_USERNAME/back:$TRAVIS_BUILD_NUMBER
  - docker tag back $DOCKER_USERNAME/back:latest
  - docker push $DOCKER_USERNAME/back:latest
