language: java

jdk:
 - openjdk8
 
services:
 - docker
 - docker build -t kubernetes .

script:
 - mvn install
 
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker tag kubernetes $DOCKER_USER/kubernetes:$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_USER/kubernetes:$TRAVIS_BUILD_NUMBER
  - docker tag kubernetes $DOCKER_USER/kubernetes:latest
  - docker push $DOCKER_USER/kubernetes:latest
