language: java

jdk:
 - openjdk8
 
services:
 - docker
 

script:
 - mvn install
 
before_install:
  - docker build -t $DOCKER_USERNAME/kubernetes .
script:
  - docker images $DOCKER_USERNAME/kubernetes
  
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push $DOCKER_USERNAME/kubernetes;
    fi
  
