language: java

jdk:
 - openjdk8
 
services:
 - docker
 

script:
 - mvn install
 
before_install:
  - docker build -t vishaldorage/kubernetes .
script:
  - docker images vishaldorage/kubernetes
  
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push vishaldorage/kubernetes;
    fi
  
