language: java

jdk:
 - openjdk8
 
services:
 - docker
 
script:
 - mvn install
 - docker build -t kubernetes .
 
after_success:
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
 - docker tag kubernetes $DOCKER_USERNAME/kubernetes:$TRAVIS_BUILD_NUMBER
 - docker push $DOCKER_USERNAME/kubernetes:$TRAVIS_BUILD_NUMBER
 - docker tag kubernetes $DOCKER_USERNAME/kubernetes:latest
 - docker push $DOCKER_USERNAME/kubernetes:latest
