language: java

jdk:
 - openjdk8
 
services:
 - docker

script:
 - mvn install
 - docker build -t travis .
 
after_success:
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
 - docker build -t travis-ci-build-stages-demo .
 - docker images
 - docker tag travis-ci-build-stages-demo $DOCKER_USERNAME/travis-ci-build-stages-demo
 - docker push $DOCKER_USERNAME/travis-ci-build-stages-demo
