language: java

jdk:
 - openjdk8
 
services:
 - docker

script:
 - mvn install
 - docker build -t kubernetes .
 
after_success:
 - docker login -u $DockerHub_User -p $DockerHub_Password
 - docker tag kubernetes $DOCKER_USER/kubernetes:$TRAVIS_BUILD_NUMBER
 - docker push $DOCKER_USER/kubernetes:$TRAVIS_BUILD_NUMBER
 - docker tag kubernetes $DOCKER_USER/kubernetes:latest
 - docker push $DOCKER_USER/kubernetes:latest
